title: Industrial Workers of the World · Maple City
email: IWW.MapleCity.GMB@Protonmail.com
baseurl: ""
url: "https://iww-maple-city.github.io"
description: The latest news and happenings from the Maple City Industrial Workers of the World! · An injury to one is an injury to all.

future: true

paypal: "paypal@iww.nyc"

logo: /assets/logo.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/social.png

twitter_username: MCINGMB
instagram_username: iwwnyc
facebook_username: MapleCity7
mastodon_username: iwwnyc
github_username: iww-maple-city
keybase_username: iwwnyc

social:
  name: IWW MapleCity GMB
  links:
    - https://twitter.com/MCINGMB
    - https://instagram.com/iwwnyc
    - https://facebook.com/MapleCity7
    - https://mastodon.social/@iwwnyc
    - https://github.com/iww-maple-city
    - https://keybase.io/iwwnyc

twitter:
  username: iwwnyc
  card: summary

facebook:
  publisher: iwwnyc

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"
