title: Industrial Workers of the World · Maple City
email: IWW.MapleCity.GMB@Protonmail.com
baseurl: ""
url: "https://iww-maple-city.github.io"
description: The latest news and happenings from the Maple City Industrial Workers of the World! · An injury to one is an injury to all.

future: true

paypal: "IWW.MapleCity.GMB@Protonmail.com"

logo: /assets/logo.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/social.png

twitter_username: MCINGMB
facebook_username: MapleCity7
github_username: iww-maple-city

social:
  name: IWW MapleCity GMB
  links:
    - https://twitter.com/MCINGMB
    - https://facebook.com/MapleCity7
    - https://github.com/iww-maple-city

twitter:
  username: MCINGMB
  card: summary

facebook:
  publisher: MapleCity7

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/

paginate: 5
paginate_path: "/news/:num/"

frame_padding: 10px

column: 3
column_gap: 30px
row_gap: 30px

small_screen:
  column: 2
  column_gap: 10px
  row_gap: 10px

process:
  keep_order: True
  album:
    sort_by_time: True # False: sort by filename
    order_by: create # access, modify
    reverse: True
  photo:
    sort_by_time: False
    order_by: modify
    reverse: True
    min_width: 600
    watermark:
      thumbnail: False
      original: True
      fontsize: 40
      fontfamily: Eczar-Medium.ttf
      rotate: 0

sass:
  sass_dir: _sass
  style: compressed
